# -*- coding: utf-8 -*-
"""CDA103_PYTHON

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nubWv5cvZtu43I5BcKNWB01E1mDUclkr
"""

c = input("Enter a number: ")
print(c, type(c))

c = input("Enter a first number: ")
c1 = input("ENter a second number: ")
F  = c + c1
print(F, type(F))

s = (eval (input("Enter a first number: ")))
s2  = (eval(input("Enter a Second number: ")))
T = (s*s2)
print(T, type(T))

"""explicit data type conversion"""

del print # remove the variable shadowing the built-in print function
f1 = (int(input("Enter a first number: ")))
f2 = (int(input("Enter a second number: ")))
print(f1, type(f1), f2, type(f2))

f1 = float(input('Enter a first number: '))
f2 = float(input('Enter a second number: '))
(f1, type(f1), f2, type(f2))

"""data type conversion :
int() can be converted from float to integer and string to integer (prvide the string contains the string contains an integer value)

float can convert from int to float And string to float (provided the string contains a numeric value)
str() can convert any numeric t0 string
"""

x = "10"
z6 = float(x)
print(z6 , type(z6))# conversion of str

"""Assignment"""

x = 11
y = 3
z = (x,y)
print(z)
x,y,z = 3,5,7
print(x,y,z)

"""

```
# This is formatted as code
```
The reason we use a temp variable is to prevent data loss. Let's say you have two variables, x and y, with initial values.

If you tried to swap them directly like this:

x = y (The original value of x would be overwritten and lost)
y = x (Now y would just get the new value of x, which is the original value of y, so both x and y would end up with the same value as y's original value)
To avoid this, the temp variable acts as a temporary storage:

temp = x: We first store the original value of x in temp.
x = y: Now, we can safely assign the value of y to x, because x's original value is preserved in temp.
y = temp: Finally, we assign the value from temp (which was the original value of x) to y.
This three-step process ensures that both original values are maintained and correctly swapped. While Python offers a more concise way to swap variables using tuple assignment (x, y = y, x, as shown in cell -46loH1zQDYS), understanding the temp variable method is fundamental to computer science concepts of variable assignment and memory management.
"""

x = 5
y = 7
temp = x #temp = 5 ,x = 5 ,y = 7
x = y #temp = 5, x = 7, y = 7
y = temp #temp = 5, y = 5, x = 7
print("after swappin:", x,y)

"""variable names and identifiers*<br>
The identifiers are the variables that are used in the program.There are certain rules about how identifiers are formed:<br>
Rule 1: Every identifier must begin with a letter (  a-z or A-Z) or an underscore (_) which may be followed bay an sequence of letters, digits or underscores<br>
Rule2: identifiers are case sensitive ( "var" and Var are wo different identifiers<br>
Rule3:identifiers can not be reserved words or key words like true, false , none, and, or, as, assert, break, class, continue ,pass, raise etc.

"""

var = 25
print(var)

"""**OPERATORS AND EXPRESSIONS**

Basic operators in python<br>
1. arithematic operators
2. comparison operators
3. logical operators
4. assignment operators
5. Conditional operators

*Arithematic operators*<br>
"""



a = 8
b = 4
print(a+b)
print(a-b)
print(a*b)
print(a/b) #it gives division result in a float form
print(a//b) #it gives quotient
print(a%b) #will give a reminder
print(a**b) #it worsk(*)as multipplication, as well(**)for square root , so here it is , 8 to the power 4

"""**comparison** **operator** **always** **returns** a **boolean** **value**"""

a = 8
b = 4
print(a == b) #check whether the value of operands are same or not.if they are it returns TRUE,otherwis FALSE
print(a!= b) #check whether the value of operands are same or not.if they weren't equal, returns TRUE,otherwise FALSE
print(a>b)
print(a<b)
print(a>=b)
print(a<=b)

"""Assignment operator"""

a = 6 #it means assigning a value from rigth operand/literal to right operand/literal
b = 5
a+=b #it mean a = a + b add and assign
print(a)
a+=b # it mean a = a + b
print(a)
b+=a  #it means b = a+b
print(b)
a+=b #it means a = a + b
print(a)
a*=b
print(a)
b/=a
print(b)
a%=b
print(a)
a//=b
print(a)

"""Bitwise operators

"""

a = 8
b = 4

"""PRACTICE"""

name = input("Enter a name: ")
age = int(input("Enter a age: "))
print(f"Hello {name} you are {20} years old") #curved brackets are using to displaye value of variable

x = int(input("Enter a first integer: "))
x1 = int(input("Enter a second integer: "))
sum = x + x1
prod = x*x1
diff = x - x1
Quotient = x/x1
print(f"the sume is {sum} ",f"the product is {prod}",f"the difference is {diff}", f"the quotient is {Quotient:.2f}")

num = int(input("Enter an integer: "))
num1 = float(input("Enter a float: "))
add = num + num1
print(f"the sume is {num + num1}", type(num), type(num1))

x = float(input("Enter a number: "))
x1 = int(x)
x2 = str(x)
print(x1,type(x1), x2,type(x2))

ply1 = int(input("Enter a score of 1 player: "))
ply2 = int(input("Enter a score of 2 player: "))
scores = ply1 , ply2
print("Before swapping their scores: ",scores)
#squares of their scores
furqan = ply1**2
arfad  = ply2**2
print("After squaring their scores: ", furqan , arfad)


#swap their sqr_score without using third variable
temp = furqan
furqan = arfad
arfad = temp
print("after swapping the playesr: ",furqan, arfad)