# -*- coding: utf-8 -*-
"""CDA103-Aug-2025-B2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12CMlMejOoR7mwri9J-8L0mvvFX3OWnVz
"""

print("My name is Joydeep")

x="Hello World"
print(x)

type(x)

"""*Taking input from the users*"""

c1=input("Enter first number: ")
c2=input("Enter second number: ")
z=c1+c2
print(z, type(z))

c1=eval(input("Enter first number: "))
c2=eval(input("Enter second number: "))
print(c1, type(c1), c2, type(c2))
z=c1*c2
print(z, type(z))

"""Explicit Data type conversion"""

i1=int(input("Enter first number:"))
i2=int(input("ENter second number: "))
print(i1, type(i1), i2, type(i2))

f1=float(input("Enter first number:"))
f2=float(input("ENter second number: "))
print(f1, type(f1), f2, type(f2))

x=10.6
i3=int(x)
print(i3, type(i3))

x="10.25"
f3=float(x)
print(f3, type(f3))

x="10.5a"
s3=str(x)
print(s3, type(s3))

"""int() can convert from float to integer and string to integer (provided the string contains an integer value)<br>
float() can convert from int to float and string to float (provided the string contains a numeric value)<br>
str() can convert any data to string

*Assignment*
"""

x=10
y=5
x,y,z=2,3,5
print(x,y,z)

x,y=10,5
print("Before Swapping: ", x,y)
x,y=y,x
print("After Swapping: ",x,y)

x=5
y=7
temp=x #temp=5, x=5, y=7
x=y #temp=5, x=7, y=7
y=temp #temp=5, x=7, y=5
print("After swapping: ", x,y)

"""*Variable names and identifiers*<br>
The identifiers are the variables that are used in the program. There are certain rules about how identifiers are formed:<br>
Rule 1: Every identifier must begin with a letter (a-z or A-Z) or an underscore ( _ ), which may be followed by any sequence of letters, digits or underscores<br>
Rule 2: Identifiers are case sensitive ("var" and "Var" are 2 different identifiers)<br>
Rule 3: Identifiers cannot be reserved words or keywords like True, False, None, and, or, as , assert, break, class, continue, pass, raise etc.
"""

True=2
print(True)

"""**Date: 24.10.2025, Lab Assignments**

*Problem 1*
"""

name=input("Enter your name: ")
age=input("enter your age: ")
print("Hello", name, "you are", age, "years old")

name=input("Enter your name: ")
age=input("Enter your age: ")
print(f"Hello {name}, you are {age} years old!")

"""*Problem 2*"""

num1=int(input("Enter 1st number: "))
num2=int(input("Enter 2nd number: "))
sum=num1+num2
diff=num1-num2
prod=num1*num2
div=num1/num2
print(f"Sum = {sum}, Difference = {diff}, Product = {prod}, Division = {div:.2f}")

"""*Problem 3*"""

num1=int(input("Enter an integer number: "))
num2=float(input("Enter a decimal number: "))
sum=num1+num2
print(f"The sum of {num1} and {num2} is {sum}")

"""*Problem 4*"""

numf=float(input("Enter a floating point number: "))
numi=int(numf)
nums=str(numf)
print(f"The number in float format is {numf} (type: {type(numf)}), in integer format is {numi} (type: {type(numi)}), and in string format is {nums} (type: {type(nums)})")

"""*Problem 5*"""

x=input("Enter 1st number: ")
y=input("Enter 2nd number: ")
print(f"Before swapping: x = {x}, y = {y}")
x,y=y,x
print(f"After swapping: x = {x}, y = {y}")

"""*Problem 6*"""

a=eval(input("Enter a: "))
b=eval(input("Enter b: "))
c=eval(input("Enter c: "))
res=(a+b)**2-4*a*c
print(f"The results is {res}")

"""*Problem 7*"""

num_i=int(input("Enter an integer: "))
num_f=float(input("Enter a floating number: "))
num_s=input("Enter a number: ")
num_sf=float(num_s)
sum=num_i+num_f+num_sf
print(f"The final sum is {sum} and type is {type(num_sf)}")

"""*Problem 8*"""

x=eval(input("Enter 1st number: "))
y=eval(input("Enter 2nd number: "))
result=(x**2+y**2)/(x+y)
print(f"The result is: {result:.3f}")

"""*Problem 9*"""

a=b=c=5
a=2
print(a,b,c)

"""*Problem 10*"""

r=eval(input("Enter radius of a circle: "))
area=(22/7)*(r**2)
circum=2*(22/7)*r
print(f"\nFor a circle with radius {r}: \n\nArea={area:.2f} \n\nCircumference={circum:.2f}")

"""**Operators and Expressions**

Basic Operators in python<br>
1. Arithmetic Operators<br>
2. Comparison Operators <br>
3. Logical Operators <br>
4. Assignment Operators <br>
5. Conditional Operators

*Arithmetic Operators*
"""

a=10
b=3
print(a+b)
print(a-b)
print(a*b)
print(a/b) #Division result in float
print(a//b) #Quotient in integer
print(a%b) #Remainder
print(a**b) #10 to the power of 3

"""*Comparison Operator*"""

a=10
b=10
print(a==b) #Checks whether the values of the operands are same or not. Returns True if same, False otherwise
print(a!=b) #Checks whether the values of the operands are same or not. Returns True if they are not same, False otherwise
print(a>b) #Returns True if a>b
print(a<b) #Returns True if a<b
print(a>=b) #Returns True if a is greater than or equal to b
print(a<=b)

"""*Assignment Operator*"""

a=10 #Assigns values from right operand/literal to left operand
b=3
a+=5 # a=a+5 Add and Assign
print(a)
a-=1 #a=a-1 Subtract and Assign
print(a)
a*=3 #a=a*3 Multiply and Assign
print(a)
a/=2 #a=a/2 Division and Assign
print(a)
a//=2 #a=a//2 Floor division and Assign
print(a)
a%=4 #a=a%4 Mod and Assign
print(a)
a**=5 #a=a**5 Exponent and Assign
print(a)

"""*Bitwise Operators*"""

a=10 #In binary a=1010. Internally integers are represented using 32 bit signed numbers. a=0000 0000 0000 0000 0000 0000 0000 1010
b=6 #In binary b=0110. Internally b=0000 0000 0000 0000 0000 0000 0000 0110
print(a&b) #Bitwise AND-ing
print(a|b) #Bitwise OR-ing
print(a^b) #Bitwise XOR-ing
print(~a) #Bitwise flip 1111 1111 1111 1111 1111 1111 1111 0101 in 2's complement. In Sign and Magnitude - 0000 0000 0000 0000 0000 0000 0000 1011
print(a<<2) #Left shift 2 bits. a=1010. Shifting left by 2 bit produces 101000. Multiplies by 4
print(a>>1) #Right shift by 1 bit. Divides by 2

"""*Logical Operator*"""

a=10
b=5
print((a==10) and (b==4))
print((a==10) or (b==4))
print(not(a==10))

"""*Membership Operators*"""

a="amolfi"
print("m" in a) #Evaluates to True if the element is a member of the set or sequence
b=[1,2,3,4,5]
print(3 in b)
print("n" not in a)

"""Suppose an expression contains multiple operators. Like 10+2*5/6+9-7, how will the same be evaluated. Look for operator precedence.<br>
Precedence List<br>
1. ** <br>
2. ~,+,- Unary operators <br>
3. *,/,%,// <br>
4. +,- <br>
5. \>>, << <br>
6. \& <br>
7. \|,^ <br>
8. \>=,>, <=, < <br>
9. == !=<br>
10.=, +=,-=,*=,/=, %=,//=, **= <br>
11. in, not in <br>
12. not, or, and

Consider a case where an expression has several operators with same precedence<br>
10+3\*7\/2\%3\//2+3-2\*2\/3<br>
In this case what would be the sequence of the operations?<br>
In these cases we need to look at the associativity of the operators

In case several operators have the same precedence, the associativity of the operators will determine the order in which the operators will be executed<br>
In an expression like 3\*2\/4, where \* and \/ both have the same precedence, the order of execution will be determined by the associativity of \* and \/. The associativity in this case is left to right, i.e., the left operator will be executed first. <br>
Example of left to right associativity<br>
\+, \-, \*, \/<br>
Example of right to left associativity<br>
**, Unary operators

Few Examples:
"""

x=10+3*2
print(x)

x=(10+3)*2
print(x)

x=2**3**2
print(x)

x=-2**2
print(x)

x=3+2>4*1
print(x)

x=(3+2>4 and 5-1 == 3 or 2+2 ==5) #(5>4 and 4==3 or 4 == 5 ) --> (True and False or False) --> False
print(x)

x = (3<2<8) #(3<5) and (5<8)
print(x)

x=5 & 3 == 1 # 0101 & 0011 == 1 --> 0001 == 1 --> 1 == 1 --> True
print(x)

x=2
y=3
z=(x+y)*(x**y)/(y-x)
print(z)

"""**Functions**"""

def Hello():
  print("Hello World")
  print("Hello World again")
Hello()
print("Outside Function")

def printName(person):
  print("Hello " + person)

printName("Aman")

def findSum(num1, num2=10):
  print(f"The sum of {num1} and {num2} is {num1+num2}")

a=5
b=7
findSum(a,b)



a=10
b=5
print(b<<1)
print(a&b)
print(a|b)
print(~b)

"""Write a function to check whether a triangle given its sides is a right angled triangle

The function name should be checkRightTriangle, to which the length of the sides should be passed as paramter from the calling function. In the parameter list, the length of the longest side should be passed as the first argument.
"""

def checkRightTriangle(l,a,b):
  p = l**2==a**2+b**2
  if p==True:
    print("Right Angled")
  else:
    print("Not Right Angled")

def main():
  l=eval(input("Enter the longest side: "))
  a=eval(input("Enter the second side: "))
  b=eval(input("Enter the third side: "))
  checkRightTriangle(l,a,b)
main()

"""Few Exercises"""

def f(x):
  return x**2

def g(x):
  return x+2

def h(x):
  return f(g(x))

print(h(3))

def f(a):
  return a**2

def g(a):
  return f(a) + f(a+1)

print(g(2))

def f(a):
  return a+2

def g(a):
  return a*2

def h(a):
  return f(g(a))+g(f(a))

print(h(2))

z = 5>3 == 3<4
print(z)

z = 3**2*2**3
print(z)

z = 4**2**1
print(z)

"""**Python Assignment 1**

P1
"""

def mathOperation(n1, n2):
  print(f"The sum of {n1} and {n2} is {n1+n2}")
  print(f"The multiplication of {n1} and {n2} is {n1*n2}")
  print(f"The division result of {n1} and {n2} is {n1/n2}")
  print(f"The quotient of dividing {n1} and {n2} is {n1//n2}")
  print(f"The remainder of diding {n1} by {n2} is {n1%n2}")


def main():
  num1=int(input("Enter 1st integer: "))
  num2=int(input("Enter 2nd integer: "))
  mathOperation(num1, num2)

main()

"""P2"""

def findMissing(avg, n1, n2):
  z= (3*avg)-(n1+n2)
  print(f"The missing number is {z}")

def main():
  num1=eval(input("Enter 1st number: "))
  num2=eval(input("Enter 2nd number: "))
  avg=eval(input("Enter average: "))
  findMissing(avg, num1, num2)

main()

"""P3"""

def timeConvert(tm):
  hrs=tm//60
  mins=tm%60
  print(f"{tm} minutes is {hrs} hours and {mins} minutes")

def main():
  tim=int(input("Enter time in minutes: "))
  timeConvert(tim)

main()

"""P4"""

def findAreaPeri(r):
  area=(22/7)*r**2
  circum=2*(22/7)*r
  print(f"The area of the circle is {area:.2f} and circumference is {circum:.2f}")

def main():
  rad=eval(input("Enter radius: "))
  findAreaPeri(rad)

main()

"""P5"""

def findDistance(t,a,u):
  s=(u*t)+(0.5*a*t**2)
  print(f"The distance travelled by the body is {s}")

def main():
  u=eval(input("Enter initial velocity: "))
  a=eval(input("Enter acceleration: "))
  t=eval(input("Enter time of travel: "))
  findDistance(t,a,u)

main()

"""P6"""

def centToFahr(c):
  fahr=c*9/5+32
  print(f"Temperature {c} degree celsius is {fahr} degree fahrenheit")

def main():
  cel=eval(input("Enter degree in celsius: "))
  centToFahr(cel)

main()

"""*Local variables and Global variables*"""

def func1(x,y): #Formal arguments, local variables scope only within the function body
  z=4 #local variable
  print(x,y,z)

func1(1,2)
print(x,y,z)

x=100  #Global variable
def func2():
  print(x)

func2()
print(x)

x=100
def func3():
  x=20
  print(x)

func3()
print(x)

x=100
def func4(x):
  print(x)

func4(20)
print(x)

x=100
def func5():
  global x
  x=20
  print(x)

func5()
print(x)

"""*Returning values from a function*"""

def findAreaRect(len, br):
  area = len*br
  return area

def main():
  l=eval(input("Enter length: "))
  b=eval(input("Enter breadth:"))
  a = findAreaRect(l,b)
  print(f"The area of rectangle is {a}")

main()

"""*Write a function that takes as arguments the principal amount, rate of interest per annum in percentage and the time duration. It returns the simple interest accumulated, which is printed the main funtcion*"""

def findSimpleInter(a, r, t):
  inter=a*r*t/100
  return inter

def main():
  amt=eval(input("Enter principal amount: "))
  rate=eval(input("Enter rate of interest per annum in percentage: "))
  time=eval(input("Enter time duration: "))
  interest = findSimpleInter(amt,rate, time) #Actual arguments
  print(f"The interest accumulated is {interest}")

main()

"""*Pass by value*"""

def func6(x):
  x+=1

x=1
x=func6(x)
print(x)

def func6_mod(x):
  x+=1
  return x

x=1
x=func6_mod(x)
print(x)

"""*Math Library*"""

import math
t=math.sqrt(2)
print(t)

"""sqrt(x), sin(x), cos(x), tan(x), asin(x), acos(x), atan(x), log(x), log10(x), exp(x), ceil(x), floor(x), pi, e

**Decision Structure**

Write a function that converts from celsius to fahrenheit, and the function prints "Temperature Too High" if the fahrenheit value is greater than 100. If its is lesser than 40, print, "Temperature too cold"
"""

def celToFahr(c):
  f=(9/5)*c+32
  if f>100:
    print("Temperature Too High")
  if f<40:
    print("Temperature too cold")

c=50
celToFahr(c)

"""*One way decision*"""

#Statements before if
if <condition>:
  #Statements within if
#Statements after if

"""*Two way decision*

Suppose we are given coefficients a,b, and c of a quadratic equation. We need to determine whether the roots are complex or not. If the roots are complex, then simply print that roots are complex. Otherwise print the roots of the equation.
"""

def findRoots(a,b,c):
  D=b**2-4*a*c
  if D<0:
    print("Roots are complex")
  else:
    r1=(-b+D**0.5)/(2*a)
    r2=(-b-D**0.5)/(2*a)
    print(f"The roots of the QE are {r1} and {r2}")

def main():
  a=eval(input("Enter coefficient a: "))
  b=eval(input("Enter coefficient b: "))
  c=eval(input("Enter coefficient c: "))
  findRoots(a,b,c)

main()

"""Print the roots of the Quadratic equation. if D\< 0, the print, Roots are complex. However, if D==0, print Only one root. If D\> 0, print both the roots

*Multiway decisions*
"""

def findRoots_1(a,b,c):
  D=b**2-4*a*c
  if D<0:
    print("Roots are complex")
  elif D==0:
    r=-b/(2*a)
    print(f"Only one root {r:.2f}")
  else:
    r1=(-b+D**0.5)/(2*a)
    r2=(-b-D**0.5)/(2*a)
    print(f"The roots of the QE are {r1:.2f} and {r2:.2f}")

def main():
  a=eval(input("Enter the value of a: "))
  b=eval(input("Enter the value of b: "))
  c=eval(input("Enter the value of c: "))
  findRoots_1(a,b,c)

main()

"""Suppose you want to find the maximum of 3 numbers. Write a function that does so. Do not use any math library functions."""

def findMax(a,b,c):
  if a>b and a>c:
    print(f"{a} is largest")
  elif b>a and b>c:
    print(f"{b} is largest")
  else:
    print(f"{c} is largest")

def main():
  num1=eval(input("Enter 1st number: "))
  num2=eval(input("Enter 2nd number: "))
  num3=eval(input("Enter 3rd number: "))
  findMax(num1, num2, num3)

main()

def findMax_Nested(a,b,c):
  if a>b:
    if a>c:
      print(f"{a} is largest")
    else:
      print(f"{c} is largest")
  else:
    if b>c:
      print(f"{b} is largest")
    else:
      print(f"{c} is largest")

def main():
  num1=eval(input("Enter 1st number: "))
  num2=eval(input("Enter 2nd number: "))
  num3=eval(input("Enter 3rd number: "))
  findMax_Nested(num1, num2, num3)

main()

"""*Write a program that tests whether a triangle is scalene, isoceles or equilateral, given its sides*"""

def triangleType(a,b,c):
  if a==b==c:
    print("Triangle is equilateral")
  elif (a!=b) and (a!=c) and (b!=c):
    print("Triangle is scalene")
  else:
    print("Triangle is isoceles")

def main():
  a=eval(input("Enter side a: "))
  b=eval(input("Enter side b: "))
  c=eval(input("Enter side c: "))
  triangleType(a,b,c)

main()

Side1=int(input("Enter the length of the first side: "))
Side2=int(input("Enter the length of the second side: "))
Side3=int(input("Enter the length of the third side: "))
if Side1==Side2==Side3:
  print("The triangle is equilateral")
elif Side1==Side2 or Side1==Side3 or Side2==Side3:
  print("The triangle is isosceles")
else:
  print("The triangle is scalene")

"""**Tutorial Sheet Problems 7.11.2025**"""

def isPositive(x):
  if x>=0:
    print(f"{x} is positive")
    return
  print(f"{x} is negative")

def main():
  x=eval(input("Enter x: "))
  isPositive(x)

main()

def checkEven(x):
  if x%2==0:
    print(f"{x} is even")
  else:
    print(f"{x} is odd")

def main():
  x=int(input("Enter integer x: "))
  checkEven(x)

main()

def checkAge(x):
  if x>=18:
    print("Adult")
  else:
    print("Minor")

def main():
  age=int(input("Enter age: "))
  checkAge(age)

main()

def checkTemp(t):
  if t>30:
    print("Hot day")
  else:
    print("Pleasant day")

def main():
  temp=int(input("Enter the temperature: "))
  checkTemp(temp)

main()

def checkVowel(v):
  if v=='a' or v=='e' or v=='i' or v=='o' or v=='u':
    print(f"{v} is a vowel")
  else:
    print(f"{v} is a consonant")

def main():
  v=input("Enter a character: ")
  checkVowel(v)

main()

def checkDiv(x):
  if x%5==0:
    print(f"{x} is divisible by 5")
  else:
    print(f"{x} is not divisible by 5")

def main():
  inp=int(input("Enter a number: "))
  checkDiv(inp)

main()

def checkGreater(x,y):
  if x>y:
    print(f"{x} is greater")
  else:
    print(f"{y} is greater")

def main():
  x=int(input("Enter first number: "))
  y=int(input("Enter second number: "))
  checkGreater(x,y)

main()

"""Problem 16"""

def main():
  inp=int(input("Enter marks: "))
  if inp>=90:
    print("Excellent")
  elif 70<inp<=89:
    print("Good")
  elif 50<inp<=70:
    print("Average")
  else:
    print("Fail")

main()

def main():
  x=int(input("Enter a number: "))
  if x>0:
    print("Positive")
  elif x==0:
    print("Zero")
  else:
    print("Negative")

main()

def main():
  day=int(input("Enter week day (1-7): "))
  match day:
    case 1: print("Monday")
    case 2: print("Tuesday")
    case 3: print("Wednesday")
    case 4: print("Thursday")
    case 5: print("Friday")
    case 6: print("Saturday")
    case 7: print("Sunday")
    case _: print("Invalid input")

main()

"""Problem 28"""

def main():
  x=int(input("Enter an integer: "))
  if x<0:
    print("Input Positive Number Only")
  elif x<10:
    print("Single digit")
  elif x<100:
    print("Double digit")
  elif x<1000:
    print("Three digits")
  else:
    print("More than three digits")

main()

def main():
  x=float(input("Enter a number: "))
  if x.is_integer():
    print(f"{x} is integer")
  else:
    print(f"{x} is float")

main()

"""**Assignment 2 Date: 07.11.2025**"""

def findRoots():
  a=eval(input("Enter coefficient a: "))
  b=eval(input("Enter coefficient b: "))
  c=eval(input("Enter coefficient c: "))
  D=b**2-4*a*c

  if D>0:
    r1=(-b+D**0.5)/(2*a)
    r2=(-b-D**0.5)/(2*a)
    print(f"The roots of the QE are real and are {r1:.2f} and {r2:.2f}")

  elif D==0:
    r=(-b)/(2*a)
    print(f"The root of the QE is {r:.2f}")

  else:
    re=(-b)/(2*a)
    imag=(-D)**0.5/(2*a)
    print(f"The roots of the QE are impaginary and are {re:.2f}+{imag:.2f}i and {re:.2f}-{imag:.2f}i")

findRoots()

import math
def findIntersect():
  x1=eval(input("Enter x coord of center of 1st circle: "))
  y1=eval(input("Enter y coord of center of 1st circle: "))
  r1=eval(input("Enter radius of 1st circle: "))

  x2=eval(input("Enter x coord of center of 2nd circle: "))
  y2=eval(input("Enter y coord of center of 2nd circle: "))
  r2=eval(input("Enter radius of 2nd circle: "))

  dist=math.sqrt((x2-x1)**2+(y2-y1)**2)
  if dist<r1+r2:
    print("Intersect")
  elif dist==r1+r2:
    print("Touching")
  else:
    print("Separate")

findIntersect()

import math
def findMaxHeight():
  u=eval(input("Enter initial velocity: "))
  th_d=eval(input("Enter angle of projection: "))
  th=math.radians(th_d)
  g=9.8
  ht=(u**2*(math.sin(th))**2)/(2*g)
  print(f"The maximum height reached is {ht:.2f}")

findMaxHeight()

def findComplexDiv():
  a=eval(input("Enter real part of 1st complex number: "))
  b=eval(input("Enter imag part of 1sty complex number: "))
  c=eval(input("Enter real part of 2nd complex number: "))
  d=eval(input("Enter imag part of 2nd complex number: "))
  re=(a*c+b*d)/(c**2-d**2)
  imag=(b*c-a*d)/(c**2-d**2)
  print(f"The division result is {re:.2f}+{imag:.2f}i")

findComplexDiv()

def checkLeapYear():
  y=int(input("Enter year: "))
  if y%4==0:
    if y%100!=0:
      print("Leap year")
    else:
      if y%400==0:
        print("Leap year")
      else:
        print("Not a leap year")
  else:
    print("Not a leap year")

checkLeapYear()

"""**Loops**

Input 2 numbers and find their sum
"""

n1=eval(input("Enter a number: "))
n2=eval(input("Enter a number: "))
sum=n1+n2
print(sum)

"""Input 5 numbers and find their sum

Initialize sum to 0<br>
Loop 5 times<br>
$\quad$ Enter a number<br>
$\quad$ Add the number to sum<br>
Print sum
"""

def findSum():
  sum=0
  for i in range(5):
    x=eval(input("Enter a number: "))
    sum+=x #sum=sum+x
  print(f"The sum of the numbers is {sum}")

findSum()

"""Find the sum of the first n natural numbers, where n is given as input by the user

Input the value of $n$<br>
Initialize $sum=0$<br>
Loop $n$ times<br>
$\quad$ Input a number $x$<br>
$\quad$ $sum+=x^2$<br>
Print $sum$
"""

def findSumSquares():
  n=int(input("Enter the value of n: "))
  sum=0
  for i in range(n):
    sum+=(i+1)**2
  print(f"The sum of squares of first {n} natural numbers is {sum}")

findSumSquares()

"""Print all odd numbers between $0$ and $n$ (inclusive), where $n$ is given as input by the user.

Input $n$ from the user<br>
Loop $n+1$ times incrementing $i$ from $0$ to $n$<br>
$\quad$ Check if $i$ is odd<br>
$\quad$ if $i$ is odd<br>
$\quad\quad$ Print $i$
"""

def printOdd():
  n=int(input("Enter a number: "))
  for i in range(n+1):
    if i%2!=0:
      print(i, end=" ")

printOdd()

def printOdd1():
  n=int(input("Enter a number: "))
  for i in range(n+1):
    if i%2==0:
      pass
    else:
      print(i,end=" ")

printOdd1()

def printOdd2():
  n=int(input("Enter a number: "))
  for i in range(1,n+1,2):
    print(i,end=" ")
printOdd2()

"""*Fibonacci Series*<br>
The series starts with 2 numbers $0$ and $1$. The next number in the series is the sum of the previous 2 numbers<br>
$0,1,1,2,3,5,8,13,21,34,55,89 ...$

Write a program to generate the first $n$ number of the Fibonacci series, where $n$ is taken as input from the user.

Take as input the value of $n$<br>
Let $f_i$ be the 1st number<br>
Let $f_j$ be the 2nd number<br>
Print $f_i$ and $f_j$<br>
Loop $n-2$ times<br>
$\quad$ Let $f_n=f_i+f_j$<br>
$\quad$ Print $f_n$<br>
$\quad$ $f_i=f_j$<br>
$\quad$ $f_j=f_n$
"""

def Fibonacci():
  n=int(input("Enter a number: "))
  f_i=0
  f_j=1
  print(f_i, f_j, end=" ")
  for i in range(n-2):
    f_n=f_i+f_j
    print(f_n, end=" ")
    f_i=f_j
    f_j=f_n

Fibonacci()

"""**Indefinite Loops**

*Take as input numbers from the user and find their sum. The system should prompt the user to enter a number till the user provides $-1$ as input. The value of $-1$ is not included in the sum*

Initialize $sum=0$<br>
Prompt the user to enter a number $x$<br>
if $x!=-1$<br>
$\quad$ $sum+=x$<br>
Loop till user enters $x=-1$ as input<br>
$\quad$ Prompt the user to enter another number $x$<br>
$\quad$ if $x!=-1$<br>
$\quad\quad$ $sum+=x$<br>
Print $sum$
"""

def findSum():
  sum=0
  count=0
  x=eval(input("Enter a number (-1 to exit): "))
  if x!=-1:
    sum+=x
    count+=1
  while x!=-1:
    x=eval(input("Enter another number (-1 to exit): "))
    if x!=-1:
      sum+=x
      count+=1
    if count!=0:
      avg=sum/count
    else:
      avg=0
  print(f"The sum of the numbers is {sum} and average is {avg}")

findSum()

def findSum1():
  sum=0
  count=0
  moreData="yes"
  while moreData=="yes":
    x=eval(input("Enter a number: "))
    sum+=x
    count+=1
    moreData=input("Do you want to add more data (yes/no): ")

  print(f"The sum of the numbers is {sum} and average is {sum/count}")

findSum1()

"""**Nested loops**

Try to draw the following pattern:<br>
$*\quad *\quad *\quad *$<br>
$*\quad *\quad *\quad *$<br>
$*\quad *\quad *\quad *$<br>
$*\quad *\quad *\quad *$<br>
$*\quad *\quad *\quad *$<br>

Here the number of rows and columns are taken as input from the user
"""

def printStars():
  n=int(input("Enter the number of rows: "))
  m=int(input("Enter the number of columns: "))
  for i in range(n):
    for j in range(m):
      print("*", end="  ")
    print()

printStars()

"""Now try the following pattern: <br>
$*$<br>
$* \quad *$<br>
$* \quad * \quad *$<br>
$* \quad * \quad * \quad *$<br>

Take as input only the rows $r$ from the user

Consider a 3 digit number, say 153. There are 3 digits. If we raise each digit to the power of the number of digits and find the sum, the sum equals the number itself.<br>

Thus $1^3+5^3+3^3=153$. Such a number is called as an Armstrong number. Given a 3 digit number, check whether the number is Armstrong or not.
"""

def checkArmstrong():
  x=int(input("Enter a 3 digit number: "))
  q=x
  sum=0
  while q>0:
    r=q%10
    q=q//10
    sum+=r**3
  if sum==x:
    print(f"{x} is Armstrong")
  else:
    print(f"{x} is not Armstrong")

checkArmstrong()

"""**Sequences**

**Strings**
"""

c="abcd"
type(c)

"""String is a sequence of characters, where the position of each character is numbered by an index, starting from $0$, which is the index of the leftmost character. From left to right the index varies from $0$ to $length\_of\_string - 1$. One can index a string from the right as well. The righmost character has an index of -1. Here the index varies from $-1$ to $length\_of\_string$"""

print(c[-4])

"""Aside from indexing the individual characters, we can also access a contiguous subsequence of characters in a string (substring). This operation is termed as slicing. Syntax is $<string>[start\_index:end\_index]$. This means, slicing returns the substring at the $start\_index$ and running up to, but not including the $end\_index$."""

greet="Hello World"
greet[:]

"""Concatenation and Repetition"""

s1="Hello "
s2="World"
s=s1+s2
print(s)
s3=s1*3
print(s3)

"""*Length of a string* len(str)"""

len(s)

for i in range(len(s)):
  print(s[i])

new_str=""
for i in s:
  if i !='o':
    new_str+=i
  else:
    new_str+='0'
print(new_str)

"""**String Representation**

Computer systems use industry standard encodings to represent the characters. One of the oldest and most popularly used encoding was the ASCII (American Standard Code for Information Interchange). ACII uses the numbers 0 through 127 to represent the characters that were typically present in the keyboard. ASCII is mostly US centric. However, with growing demand to represent other language characters, an extended encoding system was setup, termed as Unicode. To derive the unicode for a character use the ord() function
"""

ord('~')

chr(126)

"""*Strings are immutable*"""

greet="Hello World"
greet[1]='a'

greet="Hello World! Today is Children's Day"
greet.split()

"""Split a string on the basis of a given character (say @)"""

eid="abc_cde@gmail.com@abc.com"
eid.split('@', 2)

"""**Changing case in strings**"""

greet="hello world!"
p=greet.upper()
p_low=p.lower()
p_capital=greet.capitalize()
p_title=greet.title()
p_swap=p_title.swapcase()
print(p_swap)

"""**Trimming of the white spaces**"""

greet="       Hello World         "
l=greet.strip()
le=greet.lstrip()
ri=greet.rstrip()
print(ri)

"""**Searching and Finding**"""

words="madam there goes adam"
fo=words.find("adam")
count=words.count("adam")
prefix=words.startswith("adam")
suffix=words.endswith("adam")
print(suffix)

"""**Replace and modification**"""

sent="madam there goes adam"
p=sent.replace("adam", "am")
print(sent)
print(p)

"""**Padding**"""

greet="Hello World!"
p=greet.center(50)
la=greet.ljust(50)
ra=greet.rjust(50)
print(ra, end="")
print("!")

"""**Checking the string characteristics**"""

greet="Hell0 World!"
print(greet.isalpha()) #Check whether all the characters in the string is alphabetic
print(greet.isdigit())
print(greet.isalnum())
print(greet.isspace())
print(greet.isupper())
print(greet.islower())
print(greet.istitle())

"""**Assignment 3**

1. GCD<br>
$15)35(2$<br>
   $30$<br>
   $---$<br>
    $5)15(3$<br>
      15
      ---
      XX
"""

def findGCD():
  b=int(input("Enter the larger number: "))
  a=int(input("Enter the other number: "))
  while a>0:
    b,a=a,b%a
    if b%a==0:
      gcd=a
      break
  print(f"The GCD is {gcd}")

findGCD()

def checkPalindrome():
  p=input("Enter a string: ")
  flag=True
  for i in range(len(p)):
    if p[i]!=p[-1-i]:
      flag=False
      break

  if flag==True:
    print(f"{p} is a palindrome")
  else:
    print(f"{p} is not a palindrome")

checkPalindrome()

def checkPallin(p):
  og=p
  rev=0
  while p>0:
    d=p%10
    rev=rev*10+d
    p//=10

  if rev==og:
     print(f"{og} is a Pallindrome")
  else:
      print(f"{og} is not a Pallindrome")

def main():
    p=int(input("Enter a number: "))
    checkPallin(p)

main()

def printPyramid():
  r=int(input("Enter the number of rows: "))
  for i in range(1, r + 1):
    print(" " *(r-i), end="")

    for j in range(1, i + 1):
     print(j, end="")

    for j in range(i - 1, 0, -1):
      print(j, end="")

    print()

printPyramid()

def findAP():
  a=int(input("Enter first term(a): "))
  n=int(input("Enter number of terms(n): "))
  d=int(input("Enter common difference(d): "))
  sum=0
  #print("The AP series is: ", end="")
  for i in range(n):
    term = a+i*d
    if i<n-1:
      print(f"{term} +", end=" ")
    else:
      print(f"{term} = ", end=" ")
    sum+=term
  print(sum)

findAP()

"""**Lists in python**

Strings are sequence of characters, Lists, on the other hand are sequences of arbitrary objects
"""

myList1=[1,2,3]
myList2=[1,2,3.4,'c',"hello"]
myList3=[2*3, 6*5]
print(myList3)

"""*List comprehension*"""

myList4=[x**2 for x in range(5)]
print(myList4)

myList5=list(x+1 for x in range(1,6))
print(myList5)
type(myList5)

L1=[1,2,3]
L2=[1,2,3]
L1==L2
L1 is L2

L1=L2=[1,2,3,4,5]
L1 is L2

len(L1)

"""*Indexing, concatenating and repeating lists*"""

print(L1[2])

L1=[1,2,3]
L2=['a', 'b','c']
print(L1+L2)

print(L1*2)

"""*Slicing in lists*"""

L1=[1,2,3,4,5,6,7,8]
L1[1:9:2]

L1[1:]
L1[:7]

L1[-1::-1]

"""Unlike strings lists are mutable"""

L1[7]='a'
print(L1)

"""Iterating over the elements of a list"""

for i in L1:
  print(i, end=" ")

for i in range(len(L1)):
  print(L1[i], end=" ")

"""*Multidimensional lists*"""

ML1=[[1,2,3], [4,5,6], [7,8,9]]
print(ML1)

ML1[0][2]

"""*Accessing elements of a multidimensional list using loops*"""

for i in ML1:
  for j in i:
    print(j, end=" ")
  print()

for i in range(len(ML1)):
  for j in range(len(ML1[i])):
    print(ML1[i][j], end=" ")
  print()

"""*Adding elements to a list*"""

L2=[]
L2.append(1)
L2.append('a')
print(L2)

for x in range(5):
  L2.append(x+1)
print(L2)

"""*Append elements of a list to another list*"""

L1=["Hello", "World"]
L1.extend(L2)
print(L1)

"""Inserting an element at a given position"""

L1.insert(0,"Hi!!! ")
print(L1)

"""Removing elements from the list"""

L1.remove('a')
print(L1)

L1.pop(0)
print(L1)

"""Take 2 matrices of dimesion $3\times 2$ as input from the user. Find the sum of the 2 matrices and print"""

def createMatrix():
  M=[]
  for i in range(3):
    rowList=[]
    for j in range(2):
      p=int(input("Enter an element: "))
      rowList.append(p)
    M.append(rowList)
  return(M)

def findMatrixSum(m1,m2):
  sum=[[0,0],[0,0],[0,0]]
  for i in range(3):
    for j in range(2):
      sum[i][j]=m1[i][j]+m2[i][j]
  return(sum)


def main():
  m1=createMatrix()
  m2=createMatrix()
  sumMatrix=findMatrixSum(m1,m2)
  print(f"The resultant sum matrix is {sumMatrix}")

main()

"""Lists are sequences of arbitrary objects.

**Tuples**

Tuples are similar to lists, but are immutable. Once created cannot be modified.
"""

l1=[]  #Creating lists
t1=(1,2,3)
print(t1)
type(t1)

"""Like lists, tuples can:<br>
Contain any and different types of elements<br>
Contain duplicate elements like t1=(1,1,1,3)<br>
Be indexed exactly in the same way as lists, like t1[0], t1[1], ...<br>
Be sliced exactly in the same way as lists $t1[1:5:2]$<br>
Be concatenated like t3=t1+t2<br>
Be repeated like t3=t1*2<br>
Be nested like $t2=(1,2,3, (1,2,3))$<br>
Be passed to a function, and will result in pass-by-value rather than pass-by-reference (as in the case of lists)<br>
Be iterated over

Difference between pass by value and pass by reference
"""

def changeValue(t):
  print(f"Value in function before change {t}")
  t=5
  print(f"Value in function after change {t}")

def main():
  p=3
  changeValue(p)
  print(p)

main()

def changeList(myList):
  myList[0]="New Element"

def main():
  l1=[1,2,3,4]
  changeList(l1)   #Will change the first element of the list passed
  print(l1)

main()

t3=(1,2,3,"abc")
for i in t3:
  print(i)

t4=((1,2,3), (4,5,6), (7,8,9))
for i in t4:
  for j in i:
    print(j, end=" ")
  print()

"""**Dictionaries**

Both lists and tuples are indexed using numerical indices $t1[0], t1[1]$. However, what if we want to store index with non-numerical values?<br>
Python allows this. We can use a dictionary to store elements with keys of any types (not necessarily integers), and values of any types as well.
"""

dict={"Key1":12, "Key2":13, "Key1": 14}
#dict["Key2"]=15
dict

"""In dictionaries, the keys must be unique, values can be same.

Unlike lists<br>
dictionaries CANNOT be concatenated<br>
CANNOT be repeated<br>

Can be nested<br>
Can be passed to a function using pass-by-reference
"""

dict2={"k1":{"k11":1, "k12":2, "k13":3}, "k2":{"k21":4, "k22":5, "k23":6}}
dict2

"""Dictionaries can be iterated"""

for i in dict2:
  for j in dict2[i]:
    print(f"{j} {dict2[i][j]}", end=" ")
  print()

"""Adding elements to a dictionary"""

dict2["k3"]={"k31":7, "k32":8, "k33":9}
dict2

"""Deleting elements to a dictionary"""

dict2["k4"]=(1,2)
dict2["k5"]=(3,4)
dict2

del dict2["k5"]
dict2

dict2.pop("k4")
print(dict2)

dict2.clear()  #Remove all the elements from the dictionary
dict2.copy()   #Return a copy of the dictionary
dict2.items()  #Returns a list containing a tuple for each key value pair in the dictionary
dict2.keys()   #Returns a list of all the keys in the dictionary
dict2.get("k1") #Return  the value of the key "k1"

dict3={1:1,2:12,3:14,4:16,8:133}
#Check whether this dictionary contains a key (say 15)
l1=dict3.keys()
print(l1)
flag=False
for i in l1:
  if i==15:
    print("Found")
    flag=True
if flag==False:
  print("Not found")

if 15 in l1:
  print("FOund")
else:
  print("Not found")

"""Create a dictionary to store all the students marks in each of the 5 subjects, where the key would be the student roll number.<br>
Using the dictionary find out the average marks obtained by the students in a particular subject<br>
FInd the median marks in given subject<br>
List all the students who have failed ($<35$) in a given subject

**Recursion**
"""

def fact_iter(n):
  fact=1
  while(n>0):
    fact*=n
    n-=1
  return(fact)

p=fact_iter(5)
print(p)

def fact_rec(n):
  if n==0:
    return 1
  else:
    return n*fact_rec(n-1)

"""*Fibonacci Series*"""

def fib_rec(n):
  if n==1:
    return 0
  elif n==2:
    return 1
  else:
    return fib_rec(n-1)+fib_rec(n-2)

for i in range(1,11):
  print(fib_rec(i), end=" ")

"""GCD"""

def gcd_rec(a,b):
  if b%a==0:
    return a
  else:
    return gcd_rec(b%a, a)

print(gcd_rec(15,35))

"""**Lab Assignments 21.11.2015**"""

def checkAnagram(s1,s2):
    #s1=s1.replace(" ","")
    s1=s1.lower()
    #s2=s2.replace(" ","")
    s2=s2.lower()
    s1=sorted(s1)
    s2=sorted(s2)
    print(s1, s2)
    if s1==s2:
        return True
    else:
        return False

def main():
    s1=input("Enter a string: ")
    s2=input("Enter the other string: ")
    if checkAnagram(s1,s2)==True:
        print(f"{s1} and {s2} are anagrams")
    else:
        print("Not Anagrams")
main()

def checkIsomorphic(s1,s2):
    if len(s1)!=len(s2):
        return False
    dict={}
    for i in range(len(s1)):
        a=s1[i]
        b=s2[i]
        if a not in dict:
            if b in dict.values():
                return False
            else:
                dict[a]=b
        else:
            if dict[a]!=b:
                return False
    return True

def main():
    s1=input("Enter 1st string: ")
    s2=input("Enter 2nd string: ")
    if checkIsomorphic(s1,s2)==True:
        print(f"{s1} and {s2} are isomorphic")
    else:
        print("Not Isomorphic")

main()

def matrixProduct(M1,M2):
    C=[]
    for i in range(len(M1)):
        C_r=[]
        for j in range(len(M2[0])):
            sum=0
            for k in range(len(M1[0])):
                sum+=M1[i][k]*M2[k][j]
            C_r.append(sum)
        C.append(C_r)
            #print(sum)
    print(C)

def main():
    M1=[]
    M2=[]
    a_r=int(input("Enter the number of rows of a: "))
    a_c=int(input("Enter the number of cols of a: "))

    b_r=a_c
    b_c=int(input("Enter the number of cols of b: "))
    print("Enter data for matrix a")
    for i in range(a_r):
        Ma=[]
        for j in range(a_c):
            c=int(input())
            Ma.append(c)
        M1.append(Ma)
    print(f"Matrix a is {M1}")
    print("Enter data for matrix b")
    for i in range(b_r):
        Mb=[]
        for j in range(b_c):
            c=int(input())
            Mb.append(c)
        M2.append(Mb)
    print(f"Matrix b is {M2}")
    print("\n\nPrinting product matrix")
    matrixProduct(M1,M2)

main()

def findSum(L,i):
    if i==len(L)-1:
        return L[i]
    else:
        return L[i]+findSum(L,i+1)

def main():
    L=[1,2,3,4,5,6]
    print(findSum(L,0))

main()

def THanoi(n, frm,inter,to):
    if n==1:
        print(f"Move from {frm} to {to}")
        return
    else:
        THanoi(n-1,frm,to,inter)
        print(f"Move from {frm} to {to}")
        THanoi(n-1, inter,frm,to)

THanoi(5,"A","B","C")