# -*- coding: utf-8 -*-
"""MY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12OHEUbbozBZQgpbibs49QW-cb5ra0k0c
"""

x,y = 24, 3 #In this line, X is assigned the value 24, and Y is assigned the value 3
z = x + y #Here, z is calculated as 24 + 3, so z becomes 27.
y = 5 #In this line, the variable y is reassigned a new value, 5. The previous value of y (which was 3) is overwritten and no longer accessible through y.
print(x, y, z) # When this line is executed, Python prints the current values of x, y,and z. At this point, x is 24, y is 5 (because it was reassigned),
# and z is 27 (because it was  reassigned), and z is 27 (because it was calculated before y was reassigned).
#CONCECONCEPT That's why the output is 24 5 27. Python variables hold the last value assigned to them.



print('Hello World!!!')
print("'Happy teacher's day")
print('''he said, i'm not going to there''')
print(''' i'm AICS student,my name is mudasir''')

print(2+4)

print("2+3*6")

print(2+6*4)

x = 33
print(x)
x,y,z = 3,7,8
print(x+y+z)
x,y = 3,6
z = x + y
print(z)

x = "23"  "3"
print( type(x))

x,y = 24, 3
z = x + y
y = 5
print(x, y, z)

s = "me"
t = 3.5
print(type(t))

print( '''you know i am
 a mudasir bashir ,
 i mean student of AICS'''   )

"""A list in Python is an ordered, mutable (changeable) collection of items."""

x = ["mudasir" , 3, 209, "f" ]
print(x)#This line simply prints the entire list x to the output.

print(2+5*6)
print(3*2)
print(6+7*3)
x,y = 3,9
H = x//y
H = x/y
print(H)
print("3*3+4")
x, y, z = "greatful" , "me", "yes"
print(x, y, z)

f = 6.7
t = "109"
s = 9//5
x = 5/7
print(type(x))
print(s)
print(type(t))
print(type(f))

"""here we focuses on demonstrating different ways to slice a Python list using indices and steps.
These examples show how flexible list slicing is for extracting specific parts or copies of a list.
"""

x = [3, 4, 82, 7, 9, 13, 0, 12] #This line initializes a list named x with eight integer elements.
print(x[1:3])
print(x[0:5:2])#This slice includes a step. It starts at index 0 (3), goes up to, but not including, index 5 (13), and takes every second element. So it takes elements at indices 0, 2, and 4. The output is [3, 82, 9].
print(x[3::2])#Here, the start index is 3 (7), and the end index is omitted, meaning it goes to the end of the list. The step is 2. So it takes elements at indices 3, 5, and 7. The output is [7, 13, 12].
print(x[::1])#This is a full slice from the beginning to the end, with a step of 1. It effectively creates a shallow copy of the entire list. The output is [3, 4, 82, 7, 9, 13, 0, 12].
print(x[::])#This is similar to the previous one; omitting both start and end indices, and using the default step of 1, also creates a shallow copy of the entire list. The output is [3, 4, 82, 7, 9, 13, 0, 12].

"""Certainly! This cell continues to explore Python list slicing, especially using negative indices and steps, and also demonstrates the type() function.

Let's re-examine z = [3, 4, 82, 7, 9, 13, 0, 14].

1) print(z[-3:-1])

start = -3 (which is the element 13)
stop = -1 (which is the element 14)
step is omitted, so it defaults to +1.
When the step is positive, the slice moves from start towards higher indices until it reaches (but does not include) stop.
Here, starting at z[-3] (13), a step of +1 moves to z[-2] (0). The next element would be z[-1] (14), but the slice stops before the stop index. So, it successfully collects 13 and 0.
Output: [13, 0]

2) print(z[-7:-1:-3])

start = -7 (which is the element 4 at index 1)
stop = -1 (which is the element 14 at index 7)
step = -3
When the step is negative, the slice moves from start towards lower indices until it reaches (but does not include) stop.
In this case, you're starting at z[-7] (which is 4). To move with a negative step (-3), you need to go to smaller indices (e.g., z[1 - 3] = z[-2]).
However, your stop index (-1, which is index 7) is a higher index than your start index (-7, which is index 1). You're telling Python to start at 4 (index 1), step backwards, but stop before 14 (index 7). Since stepping backwards from index 1 will never reach index 7, the slice finds no elements.
Output: [] (an empty list)

Key Rule for Slicing:

If step is positive, start must be less than stop for the slice to yield results.

If step is negative, start must be greater than stop for the slice to yield results.

Since in z[-7:-1:-3], the effective start index (1) is less than the effective stop index (7), and the step is negative, the slice correctly returns an empty list because it can't move from 1 to 7 by stepping backwards.
"""

z = [3, 4, 82, 7, 9, 13, 0, 14]
print(z[-3:-1])
print(z[-1::-2])
print(z[-4:-1:2])#This starts at z[-4] (which is 9), goes up to, but not including, z[-1] (which is 12), with a step of 2. So it takes z[-4] (9) and z[-2] (0). The output is [9, 0].
print(z[-7:-1:-3])#This tries to slice from z[-7] (which is 4) to z[-1] (which is 12) with a negative step of -3. Since the start index (-7) is before the end index (-1) in the forward direction, and you're using a negative step, Python cannot find a path to slice, resulting in an empty list. The output is [].
print(z[::-1])
print(z[::1])
print (type(z))

x = [2, 4, 3, 6, 6, 6, 9, 9, 3, 0, 2]
x.append("mudasir")
print(x)
x.remove(2)
print(x)
x.remove(9)
print(x)
print(x.count(6))
print(x.index(9))
x.insert(4,"me")
print(x)

"""x = [4,6,7,8]: This line initializes a list named x with four integer elements: 4, 6, 7, and 8.

x.extend([1,0,2]): The extend() method is used here to add all the elements from the list [1,0,2] to the end of the existing list x. So, x becomes [4,6,7,8,1,0,2].


x = [2,3,4,6,[7,1,[3,4,6],9]]: This line reassigns x to a completely new list. This new list is a nested list, meaning it contains other lists as its elements. The last element [7,1,[3,4,6],9] is itself a list, and it contains another nested list [3,4,6].

print(x[4]): This accesses and prints the element at index 4 of the new list x. Since Python uses 0-based indexing, the element at index 4 is the nested list [7,1,[3,4,6],9]. Output: [7, 1, [3, 4, 6], 9]

print(x[0]): This accesses and prints the element at index 0 of list x, which is 2. Output: 2

print(x[4][0]): This performs a nested indexing operation. First, x[4] accesses the inner list [7,1,[3,4,6],9]. Then, [0] accesses the element at index 0 within that inner list, which is 7. Output: 7

print(x[4][2][1]): This involves three levels of nested indexing:

x[4] gives [7,1,[3,4,6],9].
[2] then accesses the element at index 2 within that list, which is [3,4,6].
[1] then accesses the element at index 1 within [3,4,6], which is 4. Output: 4
"""

x = [4,6,7,8]
x.extend([1,0,2])
print(x)
x = [2,3,4,6,[7,1,[3,4,6],9]]
print(x[4])
print(x[0])
print(x[4][0])
print(x[4][2][1])

True
False
print(3 == 3)
print(3 != 3)
print(3 != 2)
print(not True)
print(not False)

print('Hello,Python')
print('hello,python')

"""# New Section 6sept lab class"""

x = [1,3,4,5,7,8]
x[2]=85
print(x)
y = { "name": "pankaj" } # Changed y to a dictionary and used a string key
print(y)
y["n"] = "s" # This operation is now valid for a dictionary
print(y)

x = [6,7,8,9,2,[3,4,5,[4,3,"arfad",6],2,1]]
print(x[5][3][2][1])

x = int(input("Enter any number: "))
print("the table of my number is: ", x,6*x,7*x,2*x,4*x,9*x,"and so on")

x = int(input("number"))
if x < 14:
  print("he was her x")
elif x == 14:
  print("she is a gold digger")
else:
  print("he was not her x")

Score = int(input("score progress record"))
if Score > 90:
    print("grade A")
elif Score > 75:
    print("grade C")
elif Score < 80:
    print("grade B")
else:
    print("Grade D and Fail")

"ask the user for the number of equal sides in a triangle"
user_input = int(input("enter the number of equal sides (0,2 or 3):"))
if user_input == 3:
  print("an equilateral triangle")
elif user_input == 2:
  print("an isoclese triangle")
elif user_input == 0:
  print(" A sacelen Triangle ")
else:
  print( " that's, undefined ")

x = ["a,e,i,o,u"]
if x == ["a,e,i,o,u,g"]:
  print(" vowels ")
else:
  print("its  consonent")


  c = input("Enter your character")
  if c in ["a","e", "i","o","u"]:
    print("your caharacter is a vowel")
  else:
    print(" your character is a consonant")

char = input("Enter a single character")
char = char .lower()

if len(char) == 1 and char .isalpha():
  if char in 'aeiou':
    print(char, "is a vowel")
  else:
    print(char, ' is a consonant')
else:
  print("this is a invalid input, please enter a single alphabet character")



"""# 13sept"""

numbers = [3, 7, 8, -9, -4, -1, 2]
for x in numbers:
   print(x**2)

numbers = [3, 4, -1, 9, -3, 8, -2, 7]
Neg_num = []
for x in numbers:
  if x < 0:
    Neg_num.append(x**2)
print(Neg_num)

numbers = [3, 4, -1, 9, -3, 8, -2, 7]
Neg_num = []
for x in numbers:
  if x < 0:
    print(x**2)

numbers = [3, 4, -1, 9, -3, 8, -2, 7]
Neg_num_sqr = []
for x in numbers:
  if x < 0:
    Neg_num_sqr.append(x**2)
print( Neg_num_sqr)

"""27 SEPT"""

c = [ 3,4,6,7]
total = sum(c)
x = len(c)
mean = total/x
print(mean)

A = [ 5,6,7,8,1,9,2]
A1 = sorted(A)
n = len(A)
idx = n//2
median = A1[idx]
print(median)
print(A1)


median = sorted(A)[len(A)//2]

A = [1,2,3,4]
median = sorted(A)[len(A)//2]
print(median)
_median = sorted(A)[len(A)//2-1]
print(_median)
m1 = (median + _median)/2
print(m1)

A = [4,2,7,8,2,4,4,]
S1 = len(A)//2 -1
print(S1)

def find_median(data):
 if len(data)%2 == 0:
  median = (sorted(data)[len(data)//2])
 else:
  median = (sorted(data)[len(data)//2] + sorted(data)[len(data)//2-1])/2
 return median



def find_median(data):
 if len(data)%2 == 0:
  median = (sorted(data)[len(data)//2])
 else:
  median = (sorted(data)[len(data)//2] + sorted(data)[len(data)//2-1])/2
 return median

A = [1,2,3,4,5]
B = [1,2,3]
print(find_median(B))
print(find_median(A))

"""REPEAT (PRACTICE): 30/10/25 DATA STRUCTURE"""

#START FROM LISTING : BASICS
list_1 = [2,3,4,6,8,9,7] # total indexes inside the list = 6
list_1.append(22)
print(list_1)

list_2 = [22,45,3,4,3,6] #lst with 5 indexes
list_2.remove(45)#this is fucn to remove something in a list
list_2.count(3)# fucn to count
print(list_2) #print fucn displays the result

list_2 = [22,45,3,4,3,6,8,9,7] #lst with 8 indexes
list_2.insert(4,2)
print(list_2)

list_z = [3, 5, 6, 7, 10, 9, 4,] # list with 7 elements and 6 indexes
x = list_z
print(x[0:])
print(x[:3])#from 0-2 but exclude 3
print(x[2:6:2])#it means exclude 6 but include 5 #expected result = 10,4
print(x[])

x = [3, 5, 6, 7, 10, 9, 4,]
x.extend([24,5])
print(x)

"""Negative listing , here we asign a list to variable x3 , #slicing"""

x3 = [1, 4, 6, 7, 9, 8, 10, 11, 13, 15, 34]
print(x3[-1:-6:-2])
print(x3[::-6])
print(x3[-1:-9:-1])
print(x3[-6:-1:1])
print(x3[-8::-1])

list_2 = [ 1, 3, 5, 10, 17, 6]
list_2.insert(2,"mudasir")
print(list_2)
list_2.remove(10)
print(list_2)
print(list_2.index(17))

"""NESTED LIST :"""

z = [ 1, 2,[6, 8, 15, [ 45,67, [ 17, 78]] ], 4, 8, 9, 10 , 11, 13, 32]
print(z[2][3][0])
print(z[2][3][2][1])

"""COMPLEX PROBLEM OF LIST"""

zx = [[[3, 4, [37, ["mehere"], 6]],], [3], [3,6 ,["helloIIT"]]]
print(zx[0][0]) # 0/p will be the whole ist list
print(zx[0][0][2])
print(zx[0][0][2][1])
print(zx[0][0][2][1][0])
print(zx[0][0][2][1][0][0])
print(zx[0][0][2][1][0][5])
print(zx[0][0][2][1][0][4])
#AN
print(zx[0])
print(zx[1])
print(zx[2])
print(zx[2][2][0][3])
print(zx[2][2][0][2])
print(zx[2][2][0][5])# here i understand that gapes in nested str( list ),cant we count

"""LIST IS A MUTABLE ,IT MEANS WE CAN DO CHANGES INSIDE IT , EVEN THOUGH WE CAN DO SLICING WITH LIST AS WELL ,STRING ..


"""

X = [ 1,2,3,4,9]
X[2] = 62 # we can only do this with int not with string
print(X)

x1 = [3, 5, 8, 10,'mudasir', 32]
x1[5]= 6
print(x1)

"""INPUT IS A INBULT COMMAND ,AND IT TAKES ALL THE VALUES AS A STRING ,IF WE GIVE IT A NUMBER FOR EXAMPLE IT WILL TAKE THAT AS A STRING, BUT WE MAKE IT STRING BY GIVING A FUCN OUTSIDE ( INT ), (FLOAT),ETC..THEN THAT VALUE BECOMES A INT / FLOAT /ETC .. WHICH WE GET FROM A USER

"""

x = int(input("Enter a number: "))
print("now multiple the numbers: ",x, 2*x, 3*x, 4*x , "and so one")

"""if / while loop"""

T_machines = int(input("how many machines whe have total : "))
if T_machines >= 13:
  print(" our system have great capability to run LLms ")
else:
  print("we have a need of some more GPUs " )

car_whb = int(input("total cars we have burn in a garage: "))
if car_whb <= 30:
  if car_whb == 30:
    print("we have need of fresh 5 cars")
  else:
    print(" we have a need of some couple of workers ")
else:
   print("Company is at downfall ")

side1 = int(input(" Enter a first side of triange: "))
side2 = int(input("Enter a second side of triangle: "))
side3 = int(input("Enter a third side of Triangle: "))
if side1 == side2 == side3:
  print("triangle is equilateral")
elif side1 == side2 != side3:
  print("triangle is isosceles")
else:
  print("scalene triangle")

x = int(input(" Enter a first side of triange: "))
y = int(input("Enter a second side of triangle: "))
z = int(input("Enter a third side of Triangle: "))

if x+y>z or y+z>x or z+x>y:
  if x == z and z == y and y == x:
    print("equilateral triangle")
  elif x == y or y == z or z == x:
    print("isosceles triangle")
  else:
    print("scalene triangle")
else:
  print("all the given sides do not form a valid triangle") #error in first condition "if"

age = int(input("Enter their valid age: "))
citizen = True #here citizensip plays a crucial role , its must
if age >= 18 and citizen == False:
  print("you are eligible for vote")
else:
  print(" you are not eligible for a vote")

original_input_char = input("Enter characters that make name of someone: ")

# This ensures the working variable 'char' is always uppercase for consistent comparison
char = original_input_char.upper()

# New condition to check if the original input was entirely lowercase
if original_input_char.islower() and original_input_char.isalpha():
    print(f"You entered '{original_input_char}'. All characters are in lowercase.")

# The rest of your logic continues to use 'char' (the uppercase version)
if len(char) == 7 and char.isalpha(): # This checks if the input is exactly 7 alphabetic characters

  if char == 'MUDASIR': # Checks for exact equality with the name
    print("yes, his name is correct")

  elif char == 'MUBASHR': # Checks for exact equality with the name
    print("No,it doesn't make sense")

  else:
     print("Name is 7 alphabetic characters, but doesn't match 'MUDASIR' or 'MUBASHR'.") # Corrected the message

else:
  print("Problem: Input is not exactly 7 alphabetic characters.") # Clarified what triggers this else block

A = ["A", "B", "D", "G", "F", "Q"]
B = []
for x in A:
 B.append(x.lower())
print(B)

age = 10
while age >=0 <=10 :
  print(age)
  age = (age-1)
print("task is executed correctly")

f_score = int(input("Enter total score of my friend"))
while f_score >50 <90:
  print("he will win the match")#it will not stop until score reaches to below
if f_score >=10 ==50:
  print("there are more cahnces, he will lose the match")
else:
  print("Error in the score list ")

password = ""
while password != "Mudasir@21": #until password not comes == .... it will deny the acess
  print("Acess is denied")
  password = (input("Enter your password: "))

print("Acess is granted")

password = ""
while password != "Mudasir@21": #until password not comes == .... it will deny the acess
 password = (input("Enter your password: "))
 if password != "Mudasir@21":
  print("Acess is denied")

print("Acess is granted")

number = int(input("Enter a number: "))
while number != 1:
  print(number)
  if number%2 == 0:
    number = number // 2
  else:
    number = number*3 + 1

print(number)

A = [10 , 30 , 40, 50, 60, 70]
m = sum(A)
n = len(A)
mean = m/n
print(mean)

def find_mean(data):
  x = sum(data)
  x1 = len(data)
  mean = x/x1
  return print(mean)

A = [30, 35, 45, 32, 10, 20,]
B = [20, 11, 15, 25, 35, 30,]
find_mean(B)

def find_mean(data):
  x = sum(data)
  x1 = len(data)
  mean = x/x1
  return print(mean)

C = input("Enter numbers separated by spaces: ")
A = C.split()
Z = []
for x in A:
  Z.append(int(x))
find_mean(Z)

def find_mean(data):
  x = sum(data)
  x1 = len(data)
  mean = x/x1
  return print(mean)

c = input("Enter numbers separated by spaces: ")
A = [int(x) for x in c.split()]
find_mean(A)

S_square = int(input( "Enter the length of a rectangle: "))
S2 = int(input("Enter the height of a rectangle : "))
Area = S_square * S2
print(Area)

S1 = float(input("Enter the Length of Sides of Square: "))
print(f"Area of a Square: {S1*S1}")

x = input("Enter the citizenship: ").lower() # Convert to lowercase for case-insensitive comparison
expected_citizenship = "indian" # Renamed 'checks' for clarity and to reflect its purpose

# Ask for identity status to make the logic fully testable
has_valid_identity_str = input("Does he have valid identity documents? (yes/no): ").lower()
P_Identity = (has_valid_identity_str == 'yes') # Convert input to a boolean True/False

if not P_Identity: # If P_Identity is False (i.e., no valid identity documents)
    print("Police has the authority to arrest him under section 39BNSS")
elif x == expected_citizenship and P_Identity: # If citizenship is 'indian' AND has valid identity
    print("He has the Indian citizen Ship")
else: # If has valid identity but citizenship is not 'indian'
    print("He is not Indian")

x = (input("Enter The Akshit's citizen ship: ")).lower()
Expected_citizenship = "indian"
Nationality = input("Does have a valid Nationality Document?(yes/no): ").lower()
P_nationality = (Nationality == "yes") #it will convert input to a bolean T/F

if not P_nationality:
    print("police has the Authority to Arrest him under section 39BNSS")
elif x == Expected_citizenship and P_nationality:
    print("He has the Indian citizen Ship")
else:
    print("For now he is not an Indian ? Verification is under way")

try:
     x = int(input("Enter any number: "))
     if x % 2 == 0:
        print("The number Entered is even")
     elif x % 2 != 0:
        print("The number Entered is odd")

except ValueError:
  print("invalid input")#logically correct and want to get o/p invalid ,it will come

x = int(input("Enter ist number:  "))
y = int(input("Enter the second number: "))
z = int(input("Enter the 3rd number: "))

if   (x > y and x > y):
  print(f"{x} is the greatest number")
elif (y < x and y <= z):
  print(f"{y} is not the greatest number")
elif (z < x and z >= y):
  print(f"{z} is the greatest number")
else:
  print("not valid input")

x = (int(input("Enter any number : ")))

if (x % 7 == 0):
  print(f"{x} is the multiple of 7")
else:
  print(f"{x} is not the multiple of 7\nend of the program")



"""lists:A built in data type that can stroe the st of values
it cam store Different types of Elements (str, float, int, str, etc )
"""

list_x = [ ]
list_x.append(input("Enter the names of Ist Movie: "))
list_x.append(input("Enter the names of 2nd Movie: "))
list_x.append(input("Enter the names of 3rd Movie: "))
print(list_x)

lst1 = ["m", "e", "e", "m"]
copy_lst1 = lst1.copy()
copy_lst1.reverse()

if copy_lst1 == lst1:
  print("its a palindrome")
else:
  print("not a palindrome")

Information = {'report':({'mudasir':7}, {'Studying':'IIt'},{'progress':20},{'Roll no':'ua250'}),
'Subjects':{'Mathematics':2,
         'prog&DS':1,
         'NMDS':1,
         'Capstone':1
    }
}
print(f"total Subjects i Have {Information.get('Subjects')}in The Semester Second")

animals = {'Domestics':{'cow':2,
                        'sheep':3,
                        'Goat':2
                         }}
print (f"we have 6 domestic animals{animals.get('Domestics')} and with one small Baby ")

count = 10

while count <=100:
    print(count)
    count += 10

lst = [ 1,2,3,2,1]

copy_lst1 = lst.copy()
copy_lst1.reverse()

if copy_lst1 == lst:
    print('palindrome')
else:
    print('not palindrome')

#Loops are utilize to repeat the instructions
count = 10

while count <=100:
  print(count)
  count += 5
  if count == 50:
    break

correct_password = "Themudasir"
max_attempts = 4
attempts = 0

while attempts < max_attempts:
    entered_password = input("Enter the password : ")
    if entered_password == correct_password:
        print("Access Granted")
        break
    else:
        attempts += 1
        print(f"Access Denied. You have {max_attempts - attempts} attempts left.")
else: # This 'else' block executes if the loop finishes without a 'break'
    print("Exceeded the limits! Try again later.")

_mudasir = "ig@mudasir13"
max_limits = 6
limits = 0

while limits < max_limits:
  entered_password = input("Enter the password: ")
  if entered_password == _mudasir:
    print("Access Granted")
    break
  else:
    limits += 1
    print(f"you have {max_limits-limits} attempts left")
else:
  print("Exceeded The Limits! Try Again later")

nums = 100
x = 5
while x < nums:
  x = x+5
  print(x)

numz = 100
z = 1

while numz > z:
  numz -=1
  print(numz)

lst_nums =[4, 5, 78, 56, 70, 23, 2, 5 ]
i = 0

while i < (len(lst_nums)-(1)):
  print(lst_nums[i])
  i += 1 #recognize and then understand how indexing work actually
"end the prog"

lst_nums =[4, 5, 78, 56, 70, 23, 2, 5 ]
i = 0

while i < (len(lst_nums)):
  print(lst_nums[i])
  i += 1
"end the prog"

n = 0
x = int(input("Enter the number: "))

while n < 10:
  n += 1
  print([x*n])
print("Zainab completed Their work of writing table 9")

i =[4, 5, 78, 56, 70, 23, 2, 5 ]
z = 0
x = 56

while i != x :
  z +=3
  print(i[z])
  break

x = [4, 5, 78, 56, 70, 23, 2, 5 ]

x1 = 70

i = 0
while i < len(x):
  if (x[i]== x1):
    print("found at idx: 4 ")
    break
  else:
    print('Finding')
    i += 1

"""practicing again 4/may"""

a,b = 1,5.0
sum = a + b
print(sum)
print(type(sum))



a,b = 1,5.0
x = int(5.0)
print(type(b))
#

a = 10
s = str(a)
print(type(s))

a = (int(input("Enter a number:  ")))
x = a*a
print(f"area of square = {x}")

x = int(input("Enter the first number: "))
y = int(input("Enter second number: "))
sum = x + y
print(f"Their sum = {sum}")

x = float(input("Enter first number: "))
y = float(input("Enter second number: "))
sum = x + y
avg = sum//2
print(f"their average = {avg}")

a = int(input("Enter the first number: "))
b = int(input("Enter second number: "))
if a >= b:
  print("true")
else:
  print("false")

n = 5
def fact_n(n):
    if n == 0:
        return 1
    else:
        return n * fact_n(n - 1)
print(fact_n(n))

INR = 0
def conv_usd (USD):
  INR = USD * 83
  print(f"{USD} USD = {INR} INR")
conv_usd(10)

n = [ "mango", "apple", "cherry", "Banana"]
for item in (n):
  print(item)



n = [ 1, 2, 4, 5, 6, 8, 9]
idx = 0
def prnt_elements (n):
      global idx # Declare idx as global
      if idx == len(n):
        return
      else:
        print(n[idx])
        idx += 1
        prnt_elements (n)

idx = 0 # Reset idx before calling to ensure fresh start
prnt_elements(n)

"""practice at IITP lib"""

x = int(input("Enter a number : "))
x1 = int(input("Enter a number : "))
x3 = x + x1 / 2
print(f"Their average = {x3}")

age = 18
if age >= 18 :
  print("you are eligible to vote")
else:
  print("you are not eligible to vote")

class Bankaccount:

#ESSENTIAL METHODS OF LISTS
xs1 = [2, 4, 6, 8, 90, 10, 11, 12, 16]
xs1.sort(reverse = True)
print(xs1)
xs1.append(13)
print(xs1)
xs1.remove(4)
print(xs1)
xs1.insert(4,31)
print(xs1)
xs1[6] = 15
print(xs1)
print(xs1,xs1[3])
xs1.sort()
print(xs1)
xs1.pop()
print(xs1)
xs1.reverse()
print(xs1)
print(type(xs1))
xs1.pop(3)
print(xs1)



